### ISSUE TITLE
Programmatically disable active selection.

### ISSUE THREAD

**Issue by SaraThepot** [wojtekmaj/react-calendar#103]
Hi,
I can't figure out how to disable the selected day after a selection.

There's something like a reset?

Thanks,
Sara

**Comment by wojtekmaj** [comment]
You should use tileDisabled function. Mind you, if the value returned from `tileDisabled` is changing, `tileDisabled` itself must change. Otherwise React won't detect something has changed. 

So instead of

```js
tileDisabled => ({ date }) => date === myDynamicDate
```

try something along the lines of

```js
getTileDisabled(dynamicDate) => ({ date }) => date === dynamicDate

tileDisabled={getTileDisabled(myDynamicDate)}
```

You'd probably want to cache the functions per `dynamicDate` argument so you don't end up with a function created with every render.

Perhaps #49 will be also helpful :)
