### ISSUE TITLE
Showing loader when disabled dates are incoming from a backend server

### ISSUE THREAD

**Issue by barth12** [wojtekmaj/react-calendar#110]
Hi!

I'm using React Table and it works just fine. There is a one issue I'm not sure how to figure out. I'm getting disabled dates from a backend server. But until it'll come I would like to show to the user a loader. 

This won't work...

```
                    this.state.loadingCalendar ? <div className="loader"></div> :
                 <Calendar
                        onChange={this.onChange}
                        onClickDay={(e) => this.onClickDay(e)}
                        onActiveDateChange={({ activeStartDate }) => this.passActiveDate(activeStartDate)}
                        value={this.state.date}
                        locale="pl-PL"
                        tileDisabled={({date, view}) => this.renderDisabled(date, view)}     
                    /> 
```
...because it will load a calendar every time again and again but we need only to see loader instead of dates raws. 

What's your approach on that?

Thank you!

**Comment by wojtekmaj** [comment]
I don't think I quite get your problem. Calendar is loaded once in your example. The only problem I see is that it will *render* each time the function it's in is invoked, and this is because you create functions in render function itself, so they are referentially unequal.

Easy fix will be here:

`onClickDay={(e) => this.onClickDay(e)}`

Which should be just

`onClickDay={this.onClickDay}`

The only problem will be with tileDisabled, which, as you get the data asynchronously, you will WANT to be referentially unequal. This was discussed in #49.

**Comment by barth12** [comment]
Hi,
Thank you for your answer. Yes, the logic discussed in #49 fits well here but I'm looking for some more elegant loader rather then just greying out all dates for a moment of date is fetching, something like this: https://react-table.js.org/#/story/server-side-data
Thank you anyway!

**Comment by wojtekmaj** [comment]
In that case, you will probably need to cover React-Calendar with another component which displays your shiny loader. :)

If you need any further assistance, do not hesitate to write!
