### ISSUE TITLE
Today Button

### ISSUE THREAD

**Issue by strap8** [wojtekmaj/react-calendar#115]
Hi @wojtekmaj 

I was wondering on how I would be able to create a "Today" button that would reset the view of the calendar to the month view of the current day.

**Comment by wojtekmaj** [comment]
You could reset the `value` to new Date() to select the today's date :) You could also set `activeStartDate` to the beginning of current month to just move the calendar view to the current month. Mind you, this will only work if no value is currently selected - it works as a "fallback" if no value is given.

**Comment by tceericliu** [comment]
Here's how we implemented our "Today" button with react-calendar 2.18.1 and react-dom 16.7.0:

1. In the constructor of the enclosing component:
    `this.calendarRef = React.createRef()`
2. In the render() of that same component:
    `<Calendar ref={this.calendarRef} />`
3. In the click handler of the "Today" button:
    `const calendar = this.calendarRef.current;`
    `const firstDayOfTodaysMonth = moment().date(1).toDate();`
    `calendar.setActiveStartDate(firstDayOfTodaysMonth);`

Initially, we thought that when the user clicks the "Today" button, we could simply set Calendar's `activeStartDate` prop. However, this didn't work - `activeStartDate` in Calendar's state doesn't seem to respond to this prop change, so the calendar doesn't re-render. So step 3 above uses a workaround - it calls on a specific method that will definitely change that state.

Note: We used `moment` above only because we were already using it for something else. You can replace that with the equivalent JavaScript Date manipulation, as long as you end up with a Date that is the first day of the month of "today".

**Comment by wojtekmaj** [comment]
@tceericliu Indeed, as documentation states, it's "the beginning of a period that shall be displayed by default when no value is given", so prop won't work if value is already selected.

**Comment by wojtekmaj** [comment]
Note: In React-Calendar 3.0, you can also use `activeStartDate` to control the currently displayed view, so you no longer need the "ref hack" @tceericliu mentioned in pt 3.
