### ISSUE TITLE
Custom styling and scss 

### ISSUE THREAD

**Issue by BenjaminHoppe** [wojtekmaj/react-calendar#186]
Hey, I'm a newbie and have some questions. I'm trying to use scss to style a calendar from scratch, I've imported the react-calender with no styles but don't know what to do from there. Do I need to just find class names from source code and write styles from there? Any push in the right direction would be greatly appreciated!

**Comment by wojtekmaj** [comment]
What I would do is I would look to the [original styles (in the source code)](https://github.com/wojtekmaj/react-calendar/blob/master/src/Calendar.less) and based my work on them. In cases not covered by original stylesheet you will need to look at the source code, though.

**Comment by matrixue** [comment]
Hi, Could you tell me how to import React-calendar without the style? Thank you so much!

**Comment by aktzin1** [comment]
I'm very new to this as well. I don't understand where you got the &_tile, &_days, etc. from in that css file? I'm trying it on my machine after installing calendar and all I can do is change the calendar background itself because &_ gives me errors. When really I want to modify the entire thing, like the tiles, etc.

**Comment by wojtekmaj** [comment]
@aktzin1 That's LESS file, it's later compiled to normal CSS file.

See: http://lesscss.org/features/#parent-selectors-feature
