### ISSUE TITLE
Select on MMM

### ISSUE THREAD

**Issue by drixbarsali** [wojtekmaj/react-calendar#236]
How can i get rid of the select when i choose MMM ? i just want to show plain month (jan, feb ...).

**Comment by wojtekmaj** [comment]
Hi @drixbarsali, what "select" do you mean? I'm not sure. Can you give me a screenshot?

**Comment by hkar19** [comment]
what i can see, when you set the `format` props to `"dd MMM yyyy"`, the month part will have `select` component.

how do you disable that, for example just show plain text instead of `select` component

<img width="232" alt="image" src="https://user-images.githubusercontent.com/5562429/132506011-2ff6ec7a-4987-49c0-99bd-555f1e67b7b7.png">

**Comment by wojtekmaj** [comment]
Sorry, you cannot.
