### ISSUE TITLE
Clicking on a date from the next or previous month in the current month.

### ISSUE THREAD

**Issue by abhisheknayak09** [wojtekmaj/react-calendar#275]
Clicking on date from the next or previous month in the current month, should take me to the next month, rather than staying in the same month view.

**Comment by wojtekmaj** [comment]
Hmm, that's exactly what's happening in basic implementation used e.g. on [React-Calendar's home page](http://projects.wojtekmaj.pl/react-calendar/). Can you share the implementation you're having issues with, preferably on Code Sandbox?

**Comment by abhisheknayak09** [comment]
Do we need to pass a prop for this implementation? As it is not functioning like this by default.

**Comment by mriot** [comment]
I'm having the same problem. It's working on your example page for me though.
https://codesandbox.io/s/clever-shannon-hy7zg

It seems that several event handlers are not working as well.
E.g. onViewChange does not have any impact.

**Comment by abhisheknayak09** [comment]
Any updates?

**Comment by wojtekmaj** [comment]
> I'm having the same problem

The reason you see this problem is because you use 2.x improperly - you gotta use `value` and `onChange` prop at the very least. So this:

```js
function App() {
  const [value, onChange] = useState(new Date());
  return (
    <div className="App">
      <Calendar
        onChange={onChange}
        value={value}
      />
    </div>
  );
}
```

will work. However you're right that 3.0.0-beta does have this issue. Thank you!

> onViewChange does not have any impact

onViewChange and several others were added in v3.x as a part of making React-Calendar possible to use as a fully controlled/uncontrolled component component
