### ISSUE TITLE
tileDisabled gives wrong date when returnValue is 'end'

### ISSUE THREAD

**Issue by pitops** [wojtekmaj/react-calendar#327]
Say for example I want to disable all days that are before today(including time).

if `returnValue` is set to `end` meaning the date is "03/03/2020 23:59", tileDisabled `date` variable gives "03/03/2020 00:00" as in start of day.

I believe when returnValue is set to `end` the tileDisabled `date` should do the same.

**Comment by wojtekmaj** [comment]
Tiles are defined by the date they start with. So for example February tile will be uniquely identified by Date `2020-02-01 00:00:00`. Whether you want to return begin, end or a date range on tile click is a different story.

I see where you got this confusion from, but I don't think that will be worked on, because identifiers being not unique anymore would be equally confusing, and on top of that, that would have been a breaking change.

**Comment by pitops** [comment]
I understand what you are getting at, but the identifier part should only be the `date` and not the `time` as well (internally speaking).

Being a breaking change, if its something that would bring more clarity to what is expected by an end-user **vs** what the author intended I wouldn't say that's a bad thing.

But it is your call nonetheless, thanks for the reply.
