### ISSUE TITLE
Month Switch Callback

### ISSUE THREAD

**Issue by tingus** [wojtekmaj/react-calendar#341]
You essentially have an event for every other means when it comes to clicking on elements. But when you click on next or previous to go forward or back a month there is no means of a callback.

I've utilised all your click events and unable to find a clean work around for this.

**Comment by wojtekmaj** [comment]
`onActiveStartDateChange` :)

View displayed = view + activeStartDate. Eg. February is view: month + activeStartDate Feb 1, and 2020 is view: year + activeStartDate: Jan 1 2020.

**Comment by tingus** [comment]
Thanks for your reply, but a call back would be much better that does not alter the active start date.

For example when you click going next or previous, is it possible that you can have a call back without actually changing the active start date. But it would provide the first available date as apart of the call back.

I say this because a few projects which I use this on, I myself alter the active start date for the reasons that all company bookings for that day may be fully booked. Just as an example. So if I then change the date from yours, there would be a flicker in styling between the two dates.

**Comment by wojtekmaj** [comment]
Well switching between months *is* altering activeStartDate because it's the sole purpose of Prev/Next buttons to do this :D 

Anyways - since React-Calendar 3.0, you're getting onActiveStartDate callback and it's up to you what you're gonna do with it - you can use React-Calendar as a controlled component, so you can choose not to alter activeStartDate (effectively breaking the navigation).

**Comment by tingus** [comment]
I will have to fork this and add in this option. In an ideal world having the activeStartDate update by itself would be great. But being given the option to change it would be even better.
