### ISSUE TITLE
Calendar with multiple default value

### ISSUE THREAD

**Issue by imdeepmind** [wojtekmaj/react-calendar#372]
I have an array with several dates and in the calendar, I want to highlight the dates.

Here is my code:

```
class App extends Component {
  constructor() {
    super();
    this.state = {
      name: 'React'
    };
  }

  render() {
    const date = new Date("2020 12 10");
    const date2 = new Date("2020 12 11");
    const date3 = new Date("2020 12 12");

    return (
      <Calendar defaultValue={[date, date2, date3]} />
    );
  }
}
```

Here I'm passing three dates to the calendar, but it is crashing. If I pass two dates, then it is working.

Here is the error:
```
Error in /turbo_modules/react-calendar@3.0.1/dist/umd/Calendar.js (127:11)
Invalid date: Thu Dec 10 2020 00:00:00 GMT+0530 (India Standard Time),Fri Dec 11 2020 00:00:00 GMT+0530 (India Standard Time),Sat Dec 12 2020 00:00:00 GMT+0530 (India Standard Time)
```

Here is the [stackblitz example](https://stackblitz.com/edit/react-vybrfl).

Any idea what I'm doing wrong?

**Comment by Mike-Diaz** [comment]
I believe this is the intended use for the `defaultValue` prop. 

From the docs: "defaultValue: Calendar value that shall be selected initially. Can be either one value or an array of two values. If you wish to use React-Calendar in a controlled way, use value instead."

I too need to highlight more than two dates since I want to have all federal holidays highlighted. Will have to dig deeper to find my solution.

**Comment by wojtekmaj** [comment]
Indeed you can only pass a single date or a date range. However, you can use tileClassName to pass a class name to multiple tiles.

More: https://github.com/wojtekmaj/react-calendar/wiki/Recipes#selectively-style-tiles
