### ISSUE TITLE
Not able to go to last month with arrows

### ISSUE THREAD

**Issue by akellbl4** [wojtekmaj/react-calendar#431]
**Problem:**
I'm trying to make restrictions with `minDate` and `maxDate` and I have an issue with `maxDate` when it's `2020-11-01`
When it's `2020-11-01` you are not able to go to December by arrow navigation, but if you go by month view December is available.

**Example:**
https://codesandbox.io/s/bug-with-max-date-xc9os?file=/src/App.js

**Comment by pkimbrel** [comment]
I came to open a similar issue.  When I'm in October and my "maxDate" is "2020-11-01" I don't get the "next" arrow to go to November.  If my maxDate is "2020-11-02", I get the arrow.

**Comment by pkimbrel** [comment]
...additional observation.  The same thing happens if I'm in September and have a maxDate of "2020-10-01", however, October has a few days in the view, so I'm still able to select "2020-10-01".

Is the component assuming a few days of the next month are showing?  Because in the case of October, 2020, the last day of the month is Saturday, so there are no November dates on the calendar.
