### ISSUE TITLE
How can I introduce tileContent on non-selected days

### ISSUE THREAD

**Issue by LuFernandoMG** [wojtekmaj/react-calendar#478]
Hello, I am new on all of this of React, but I need to add some tileContent (a dot) if a day match with some data from the backend.

I tried to manage this by passing a handler to the tiltContent prop, but it only works with the selected day, so it doesn't modify the days that meet the requirement. How can I add this tiltContent to every day in the calendar that meet the requirement? 

For example, here I tried to add a 'yes' string to every day that match with this if (value.getDate() % 2 === 0).

  ```
const Schedule = () => {
const [value, onChange] = useState(new Date(), []);

  function hasContent(value) {
    if (value.getDate() % 2 === 0) {
      return 'yes';
    }
  }

  return (
    <div className='Schedule'>
      <Header user='client' />
      <div className="schedule__body">
        <h1 className="schedule__title">Agenda</h1>
        <Calendar
          onChange={onChange}
          value={value}
          className=''
          next2Label={null}
          prev2Label={null}
          nextLabel={<Next />}
          prevLabel={<Prev />}
          tileContent={hasContent(value)}
        />
        <h2 className="schedule__appointments">Citas</h2>
        <Appointment />
      </div>
      <Menu user='client' />
    </div>
  );
};

export default Schedule;
```

Thanks, and sorry for my broke english.

**Comment by wojtekmaj** [comment]
Your bug is here:

```js
tileContent={hasContent(value)}
```

You pass _the result_ of `hasContent` function to `tileContent` prop, where in reality you should pass _a function itself_ to tileContent. Please also mind that you will need to adjust your tileContent function to accept arguments as they are passed by React-Calendar.

This Recipe should get you back on track: https://github.com/wojtekmaj/react-calendar/wiki/Recipes#selectively-add-content-to-tiles
