### ISSUE TITLE
Can't modify the border values for the current date due to the Button attributes overriding the --now attribute

### ISSUE THREAD

**Issue by jthornjd** [wojtekmaj/react-calendar#529]
.react-calendar__tile--now : {
  border: 2px black solid;
  border-radius: 20%
}

has no effect due to it not overriding the button attributes of border: 0; 
neither does following the recipes to change a specific tileClassName. This also gets cancelled out by the button. This is not the case when modifying .react-calendar__tile--active

**Comment by wojtekmaj** [comment]
Not sure what your CSS is, but if you apply some styling to a selector of a higher specifity then you will have these kind of issues, and the only way to fight it would be to resolve it by either making something less specific (e.g. class name applied to all `<button>`s instead of applying styles to `button` selector) or by making your calendar style more specific (`button.react-calendar__tile--now`, or adding `!important`).
