### ISSUE TITLE
Current day of the month is not being styled properly

### ISSUE THREAD

**Issue by debarghya23** [wojtekmaj/react-calendar#623]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

In the month view, the current day of the month is not being styled properly. The class responsible for styling, `react-calendar__tile--now`, is not being applied properly in the browser. It is being overriden by something else like this:

.react-calendar__tile--now {
    ~~background: #ffff76;~~
}

### Steps to reproduce

1. Install react-calendar
2. Import the `<Calendar />` component from the package
3. Import 'react-calendar/dist/Calendar.css'
4. Add the component to your code

### Expected behavior

Current day of the month should be styled like this (taken from a video):
![react-calendar-expected-behaviour](https://user-images.githubusercontent.com/64488372/178205414-598a6205-38e1-481a-87ce-67699119cd0b.png)

### Actual behavior

Current day of the month is not being styled properly.

Today is 11th of July 2022. The calendar is being displayed as below:
![react-calendar-bug](https://user-images.githubusercontent.com/64488372/178205674-8bc2fc56-eaf5-428f-989c-a00baa841f66.png)

### Additional information

![react-calendar-console](https://user-images.githubusercontent.com/64488372/178204545-fb386b60-75a7-403f-a7fd-ab5d070359d0.png)

### Environment

- **Browser (if applicable)**: 103
- **React-Calendar version**: ^3.7.0
- **React version**: ^18.2.0

**Comment by bearsworth** [comment]
It's a simple work around, and there are probably better ways to do this, but you can simply create a new state called previousDay. 

Then create a function to be called by onClickDay property of calendar. Something like this :

  const calendarClickDay = (value, event) => {
    const currentDate = Date.now(calendarValue);
    if (!prevCalendarDay) {
      console.log('new date set');
      setPrevCalendarDay(value);
      return;
    }
    const prevCalendarUnix = Date.now(prevCalendarDay);
    if (
      currentDate
      && currentDate === prevCalendarUnix
    ) {
      console.log('removing the date already set...');
      setPrevCalendarDay(null);
      document.activeElement.blur();
      return;
    }
  };

The reason I used document.activeElement.blur() is because there is a focus event on each click which leaves a gray background. Actually its rather silly but at first I wanted this feature but now I realize my app just needs to move to a next page.... so I'm sharing this here.

**Comment by wojtekmaj** [comment]
If that CSS is crossed out, it means there's another CSS rule in your app that overrides it.
