### ISSUE TITLE
Doesn't support correctly Azerbaijan language 

### ISSUE THREAD

**Issue by murafalizade** [wojtekmaj/react-calendar#631]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

Actually, the bug is I set locale props as "az".But it doesn't work correctly. For example months should be "iyul", however it was "M07". Also days of week didn't change anything. How can we fixed it. I am also ready to contribution azerbaijan language problems. Because it is so big problem for our developers.
`      <Calendar locale="az"/>
`

### Steps to reproduce

1. Create-react app
2.  Import Calendar component
3.  Set locale props  "az"

### Expected behavior

Month names should be correctly
M07 not, should be "Iyul"

### Actual behavior

Month names are M and count of months. For example now month is july, 7th months and calendar shows me M07. However it should be 'Iyul'

### Additional information

If applicable me, I can send screenshots and so on.

### Environment

- **Browser (if applicable)**:Chrome 96, Firefox 94
- **React-Calendar version**: ^3.7.0
- **React version**:^17.0.2

**Comment by wojtekmaj** [comment]
This is not the issue with React-Calendar, but Chromium. Firefox and Safari render date correctly.

Please [raise bug to Chromium project](https://bugs.chromium.org/p/chromium/issues/entry), that e.g. `new Intl.DateTimeFormat('az', { month: 'long' }).format(new Date(2022, 0, 1))` returns `"M01"` instead of `"yanvar"`.
