### ISSUE TITLE
First click chose, Second click cancel

### ISSUE THREAD

**Issue by TpTTT-T** [wojtekmaj/react-calendar#633]
### Before you start - checklist

- [x] I have checked if this feature request is not already reported

### Description

First click, chose a day.
If second click is on same day, cancel that. no style more.

It is like reset

**Comment by bearsworth** [comment]
It's a simple work around, and there are probably better ways to do this, but you can simply create a new state called previousDay.

Then create a function to be called by onClickDay property of calendar. Something like this :

// I use the onCalendarChange for the onChange part. Then I use prevCalendarDay for the value part of Calendar.
const [calendarValue, onCalendarChange] = useState(new Date());
const [prevCalendarDay, setPrevCalendarDay] = useState(null);

const calendarClickDay = (value, event) => {
const currentDate = Date.now(calendarValue);
if (!prevCalendarDay) {
console.log('new date set');
setPrevCalendarDay(value);
return;
}
const prevCalendarUnix = Date.now(prevCalendarDay);
if (
currentDate
&& currentDate === prevCalendarUnix
) {
console.log('removing the date already set...');
setPrevCalendarDay(null);
document.activeElement.blur();
return;
}
};

The reason I used document.activeElement.blur() is because there is a focus event on each click which leaves a gray background. Actually its rather silly but at first I wanted this feature but now I realize my app just needs to move to a next page.... so I'm sharing this here.
