### ISSUE TITLE
Locale doesn't work some browsers

### ISSUE THREAD

**Issue by thefidanabdulla** [wojtekmaj/react-calendar#642]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-Calendar version
- [X] I have checked if this bug is not already reported

### Description

az-AZ locale doesn't work on following browsers: Chrome, Opera, Brave. I checked another browser like edge it worked. 

### Steps to reproduce

send to locale prop this keyword: "az-AZ":
and check the browsers which I mentioned above  

### Expected behavior

I expect the month name in my own language (Sentyabr, Oktyabr)

### Actual behavior

It looks like for the M09 or M10.

### Environment

- **Browser (if applicable)**:
- **React-Calendar version**:
- **React version**:

**Comment by wojtekmaj** [comment]
Unfortunately since React-Calendar i18n depends entirely on browser's support for Intl, there's nothing I can personally do.
However, note that in our [README](https://github.com/wojtekmaj/react-calendar/) there's Intl polyfill mentioned, and this polyfill [actually supports az locale](https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/az.json.

**Comment by thefidanabdulla** [comment]
Thanks for your attention :)
