### ISSUE TITLE
Add theme support

### ISSUE THREAD

**Issue by jimmyhogerty** [wojtekmaj/react-calendar#907]
### Before you start - checklist

- [X] I have checked if this feature request is not already reported

### Description

Styling the calendar with css is limited.

### Proposed solution

Add [classNames](https://www.npmjs.com/package/classnames) and use a theme design pattern to target different areas of the calendar so that users can customize calendar accordingly.

**Comment by jimmyhogerty** [comment]
Happy to take a stab at this if it's cool by you.

**Comment by informaticadiaz** [comment]
I agree

**Comment by luixo** [comment]
Totally agree on that, there is a variety of styling technics nowadays:
- tailwind css
- libraries that expose `styled`-like objects
- CSS modules

Adding `classNames` prop will allow all this solution to be usable in calendar.
I'm up on adding this functionality as well!
(please add me as a reviewer to PR otherwise)

**Comment by silverwind** [comment]
Some overridable CSS variables for the colors would be a start. I imagine this would cover most people's themeing needs.

**Comment by silverwind** [comment]
I recently did styling for this module and I needed to do a few more like removing the border and the font changes, so at least for me, color variables would not completely replace my custom CSS, but they would get me like 90% there, so they'd still be very welcome. Should place them on `:root`.
